# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node

on:
  pull_request:
    branches: [ "master" ]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "v16.13.2"
          cache: 'yarn'
          cache-dependency-path: './app/yarn.lock'

      - name: Install packages with yarn
        working-directory: ./app
        run: yarn install

      - name: Run tests with vitest
        working-directory: ./app
        run: yarn test 
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "v16.13.2"
          cache: 'yarn'
          cache-dependency-path: './app/yarn.lock'
      
      - name: Install packages with yarn
        working-directory: ./app
        run: yarn install

      - name: Run eslint
        working-directory: ./app
        run: yarn eslint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "v16.13.2"
          cache: 'yarn'
          cache-dependency-path: './app/yarn.lock'
      
      - name: Install packages with yarn
        working-directory: ./app
        run: yarn install

      - name: Run typecheck
        working-directory: ./app
        run: yarn typecheck    



      